title: Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ntse.github.io/mobile

aux_links:
  Template Repository: https://ntse.github.io/mobile
